---
- hosts: jenkinsprod
  tasks:
   - name: checking ping connectvity
     ping:

   - name: copy file from jenkins to jenkinsprod server
     copy:
      src: /tmp/hello.war
      dest: /opt/tomcat/webapps

   - name: stop tomcat service
     shell: service tomcat stop

   - name: start tomcat service
     shell: service tomcat start
